swagger: '2.0'
info:
  title: User
  version: '1.0.0'
paths:
  /users/:
    get:
      summary: Get a list of users
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      summary: Create a new user
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: User created successfully
  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/User'
        '404':
          description: User not found
    patch:
      summary: Update user by ID
      parameters:
        - name: userId
          in: path
          required: true
          type: integer
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: User updated successfully
        '404':
          description: User not found
    delete:
      summary: Delete user by ID
      parameters:
        - name: userId
          in: path
          required: true
          type: integer
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
definitions:
  User:
    type: object
